name: 'Publish Package'
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Publishing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build on node v18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: yarn install
      # - run: yarn test:types
      - run: yarn build
      - run: yarn test
        env:
          CI: true

      - name: Publish if version has been updated
        if: success()
        uses: pascalgn/npm-publish-action@1.3.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
